### PR TITLE
test(api): updates all db connections to use same connector (BOAS-52)

### PR DESCRIPTION
**Pull request by mayya-bond-kc**
## Describe your changes

- uses same database connector across api

## Type of change 🧩

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Comment by francescobrenci-AR** [comment]
One test is failing here https://dev.azure.com/planninginspectorate/back-office/_build/results?buildId=33350&view=logs&j=4915e90a-f1c2-55b0-f3a8-aede04c03102&t=9cf4b06b-a014-5761-c739-ea55beac0826&l=203

**Comment by mayya-bond-kc** [comment]
> One test is failing here https://dev.azure.com/planninginspectorate/back-office/_build/results?buildId=33350&view=logs&j=4915e90a-f1c2-55b0-f3a8-aede04c03102&t=9cf4b06b-a014-5761-c739-ea55beac0826&l=203

Yep already looking at it

**Review by francescobrenci-AR — APPROVED** [review]

**Pull request merged**
