### PR TITLE
Feature/boas 610 update doc status and redacted api

### PR DESCRIPTION
**Pull request by DavidJWhiteDev**
## Describe your changes

BOAS-610 Add an API endpoint to update the status and redacted status of an array of documents (part of BOAS-585)
Also includes BOAS-620 which adds 2 new fields to the Document table:  createdAt, and redacted.
Also fixes BOAS-624 - Documents not displayed in descending creation order.
Also fixes BOAS-627 - Documents not displaying Received Date (created date) - raised against BOAS-584

## BOAS-610 API to change status of files
https://pins-ds.atlassian.net/browse/BOAS-610
BOAS-620 Add new fields to Document table
https://pins-ds.atlassian.net/browse/BOAS-620
BOAS-624 Documents are not displayed in the order they are uploaded in the folder
https://pins-ds.atlassian.net/browse/BOAS-624
BOAS-627 Date Received column blank when displaying files in a folder
https://pins-ds.atlassian.net/browse/BOAS-627

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [x] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [x] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Review by lutamKC — CHANGES_REQUESTED** [review]
@DavidJWhiteDev , I'm not sure where exactly in the code this is defined, so I'm just commenting here.

the field "receivedAt" currently returns a string like "2022-12-19T11:34:06.704Z" whereas normally the frontend expects dates to be returned as Date instances.
Again, I'm not sure where this should be fixed in the code but I guess the fix should be just to replace:

`...
receivedAt: receveidAtAsAString
...
` 
to
`...
receivedAt: new Date(receveidAtAsAString)
...
`

**Comment by DavidJWhiteDev** [comment]
> @DavidJWhiteDev , I'm not sure where exactly in the code this is defined, so I'm just commenting here.
> 
> the field "receivedAt" currently returns a string like "2022-12-19T11:34:06.704Z" whereas normally the frontend expects dates to be returned as Date instances. Again, I'm not sure where this should be fixed in the code but I guess the fix should be just to replace:
> 
> `... receivedAt: receveidAtAsAString ... ` to `... receivedAt: new Date(receveidAtAsAString) ... `

Ludovico, the API was storing the value in a Date type, and returning as such.  Changed to convert to a Unit Timestamp and return as a number - this is the same way that it is already done for the date in Key Dates. All Good.

**Review by francescobrenci-AR — DISMISSED** [review]

**Comment by francescobrenci-AR** [comment]
WEB looks good to me

**Review by lutamKC — DISMISSED** [review]

**Review by lutamKC — APPROVED** [review]

**Pull request merged**
