### PR TITLE
Feature/BOAS-395 create seed prod db pipeline

### PR DESCRIPTION
**Pull request by DavidJWhiteDev**
## Describe your changes

scripts etc to create a separate azure pipeline to seed the Prod database only.
This separates it from the other seed script that also adds test data, for Dev and Test environments.

## BOAS-395 Create Seed Prod Database Pipeline
https://pins-ds.atlassian.net/browse/BOAS-395

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Review by mayya-bond-kc — CHANGES_REQUESTED** [review]
LGTM. Could we please also remove the duplication of this code in the `seed.js` file?

**Comment by DavidJWhiteDev** [comment]
> LGTM. Could we please also remove the duplication of this code in the `seed.js` file?

Aah, I left that file as I know you have edited it in your branch.  OK, I will clean that up now

**Review by mayya-bond-kc — APPROVED** [review]

**Pull request merged**
