### PR TITLE
Build and Release pipelines

### PR DESCRIPTION
**Pull request by andylangridge**
## Describe your changes
- Added Build and Release pipelines

### CODE REVIEW

**Review by mayya-bond-kc — DISMISSED** [review]

**Comment by radum** [comment]
The dockerfile from web is outdated. All the folders from the packages monorepo folder should be copied in now, not just the one. Do you want to do that @andylangridge ? Or should I?

**Comment by andylangridge** [comment]
@radum I'll do that no problemo!

**Review by radum — APPROVED** [review]

**Pull request merged**
