### PR TITLE
chore(applications): consolidate dependency versions across repo

### PR DESCRIPTION
**Pull request by Maby0**
## Describe your changes

This PR consolidates the versioning of dependencies across the entire repository. This means that the root package.json has every dependency that is used in the repository listed in it with a specific version. Meanwhile, every workspace has their specific dependencies listed as `"express": "*",` which means that they'll rely on the root package.json for their versioning.
This means that the process of adding a new dependency is adding it to the root package.json with the version that you want, and then again with a `'*'` in place of a version in whichever workspace you want your dependency to be imported to.
Following this change, a small tweak I was able to make to both the Dockerfiles was adding a couple of flags to the ci call (`npm ci --workspaces --if-present`). This tells npm to only install dependencies that are required for that build (i.e. the workspaces that have been copied in), thus reducing the total installation size. 
Finally, the package-lock.json needed to be regenerated to get this to work. Upon regeneration, the amount of lines reduced from 52k to 26k which I thought was a pretty hefty amount (no more spaghetti dependencies!).

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Review by Yakitrak — APPROVED** [review]
LGTM! Thank you for doing this! All seems to be running perfectly locally and removing node_modules and doing a `npm ci`. 

For anyone else reviewing this, instead of going to each package and removing node_modules, use this command `npx npkill` which gives you the option to remove all of them. It is also much faster than doing `rm -rf node_modules`.

**Comment by beejjacobs** [comment]
@Maby0 I suggest we run the Build pipeline against this branch to check it all builds OK; and we can compare image sizes too which might be interesting to see.

**Comment by Maby0** [comment]
@beejjacobs It all seems to build without errors (the UI indicates that it's failing due to my branch name format 😄). The size difference on all apps and functions are:

Workspace | Current build size on main (MB) | PR build size (MB)
-- | -- | --
api | 2476.3 | 1397.5
web | 1454.1 | 936.4
applications-migration | 115.4 | 46.8
applications-background-jobs | 115.5 | 45.6
applications-command-handlers | 115.4 | 33.8

**Comment by beejjacobs** [comment]
> @beejjacobs It all seems to build without errors (the UI indicates that it's failing due to my branch name format 😄). The size difference on all apps and functions are:
> 
> Workspace	Current build size on main (MB)	PR build size (MB)
> api	2476.3	1397.5
> web	1454.1	936.4
> applications-migration	115.4	46.8
> applications-background-jobs	115.5	45.6
> applications-command-handlers	115.4	33.8
> Note: I needed to rework the node_modules merging pipeline step to get the correct dependencies included in the function's package.
> 
> The process now looks like this for each function:
> 
> * symlink the package-lock.json into the function's directory
> * `npm ci --omit=dev --prefix path/to/function/directory` (--prefix tells npm where to dump the node_modules)
> * remove the symlinked package-lock.json from the function's directory

That is a huge saving, great work @Maby0 ! Let's hope this passes regression :D 

Thanks for the explanation in terms of functions, seems straight forward. I'd not heard of `--prefix`, seems it is not documented either!

**Review by beejjacobs — APPROVED** [review]
LGTM! (pending regression etc...)

@francescobrenci-AR may be worth deploying from branch to DEV, then running E2E there, to catch any issues before merge?

**Comment by francescobrenci-AR** [comment]
Duplicate of https://github.com/Planning-Inspectorate/back-office/pull/2520 which solves a commit message format issue which prevents merging

**Pull request closed without merging**
